version: '3.4'

services:
  webexemplo:
    image: ${DOCKER_REGISTRY-}webexemplo
    build:
      context: .
      dockerfile: WebExemplo/Dockerfile

    networks:
      - demo_aspnet

 

  meu_mongo:
    image: mongo:3.4
#    ports: 
#     - "27017:27017"
    volumes:
      - db_mongo:/data/db
    networks:
      - demo_aspnet
    restart: always
    command: --storageEngine wiredTiger
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: idec29

volumes:
  db_mongo:

networks:
  demo_aspnet:
    driver: bridge
